### ISSUE TITLE
Error in batch run. Potential issue with source code

### ISSUE THREAD

**Issue by MaartenWynants** [dMillarARS/cQ_analysis#1]
Hello, 

I was trying out the source codes on my data and I encountered the following error when running "batchRunBfAndEvSepForCQ":
_New names:
* storm_id -> storm_id...5
* storm_id -> storm_id...9
 Error: Can't subset columns that don't exist.
x Column `storm_id1` doesn't exist._

I subsequently tried to example dataset where I encountered a similar error. I was wondering if there's a bug in the source code when naming and subsetting the different storms?

Regards,
Maarten

**Comment by MaartenWynants** [comment]
I did manage to find the specific section of the source code connected to the “processStormEventsWithConc” function (lines 236-241):

_allEventDTs <- bind_cols(peakFlowPerEvent,
                         startAndEndDTs) %>%
  select(!c(storm_id1,storm_y_n)) %>%
  rename(peak_dt = datetime,
         peak_sm_flow = smooth_st_flow)_

![image](https://user-images.githubusercontent.com/22454715/147584868-2845280b-da8a-4f9d-9186-b4bf441f40ff.png)


Given the specific error, I assumed it has something to do with the selection of storm_id. 
 

Apparently storm_id got renamed to storm_id…5 and storm_id…9. I do not know why this is the case, however, I adapted the source code to the following: 

_allEventDTs <- bind_cols(peakFlowPerEvent,
                         startAndEndDTs) %>%
  select(!c(storm_id...5, storm_y_n)) %>%
  rename(peak_dt = datetime,
         peak_sm_flow = smooth_st_flow, storm_id = storm_id...9)_

And it works after that!

**Comment by dMillarARS** [comment]
Thanks for posting! 

I was finally able to reproduce the error message above by updating tidyverse. As written, the scripts should work with tidyverse 1.3.0. The above edits appear to resolve the issue when using tidyverse 1.3.1.

**Comment by dMillarARS** [comment]
I've updated cQ_functions to resolve this issue. Should work with tidyverse 1.3.0 or 1.3.1 now. Thanks again!
